# Generated by Django 4.1 on 2024-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("carbs", models.FloatField()),
                ("protien", models.FloatField()),
                ("fats", models.FloatField()),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
