# Generated by Django 4.1 on 2024-03-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_calories", "0002_consume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food", old_name="protien", new_name="protein",
        ),
    ]
